# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='GerenteDeCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('cuentas', models.ManyToManyField(to='cuentas.Cuenta')),
            ],
            options={
                'verbose_name': 'Gerente de Cuenta',
                'verbose_name_plural': 'Gerentes de Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('abreviatura', models.CharField(blank=True, max_length=255, null=True, verbose_name='Abreviatura')),
                ('codigo_postal', models.CharField(max_length=255, verbose_name='Codigo Postal')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['provincia', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.TextField(blank=True, verbose_name='Comprobante')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Importe')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('abreviatura', models.CharField(blank=True, max_length=255, null=True, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, default=20000, max_digits=20)),
            ],
            options={
                'verbose_name': 'Perfil de Empleado',
                'verbose_name_plural': 'Perfiles de Empleado',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('abreviatura', models.CharField(blank=True, max_length=255, null=True, verbose_name='Abreviatura')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='cuentas.Pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['pais', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia', to='cuentas.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='gerentedecuentas',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.PerfilEmpleado'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Localidad', verbose_name='Localidad'),
        ),
    ]
