# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='signo',
            field=models.CharField(choices=[('1', '+'), ('-1', '-')], max_length=2, verbose_name='Signo'),
        ),
    ]
