# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20160819_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenteDeCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('cuentas', models.ManyToManyField(to='cuentas.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, default=20000, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='importe',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Importe'),
        ),
        migrations.AddField(
            model_name='gerentedecuentas',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.PerfilEmpleado'),
        ),
    ]
