# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20160823_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='gerentedecuentas',
            options={'verbose_name': 'Gerente de Cuenta', 'verbose_name_plural': 'Gerentes de Cuenta'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='perfilempleado',
            options={'verbose_name': 'Perfil de Empleado', 'verbose_name_plural': 'Perfiles de Empleado'},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='signo',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='comprobante',
            field=models.TextField(blank=True, verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Importe'),
        ),
    ]
